env_files = [{ path = "./.env.development", profile = "development" }]

[tasks.bootstrap]
script = '''
cdk bootstrap --profile $AWS_PROFILE
'''

[tasks.deploy]
script = '''
cdk deploy --profile $AWS_PROFILE ${@}
'''
dependencies = ["bootstrap"]

[tasks.destroy]
script = '''
cdk destroy --profile $AWS_PROFILE ${@}
'''
